# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./Code/Protocols/generalizeddatastructure.h \
    ./Code/Protocols/Protocols.h \
    ./Code/MainWindow/MainWindow.h \
    ./Code/CameraWidget/CameraWidget.h \
    ./Code/Communication/Communication.h \
    ./Code/TakePhotoSettingWidget/TakePhotoSettingWidget.h \
    ./Code/SystemSettingWidget/SystemControlWidget.h \
    ./Code/SerialPort/SerialPortWidget.h \
    ./Code/SelectedCamera/SelectedCameraWidget.h
SOURCES += ./Code/CameraWidget/CameraWidget.cpp \
    ./Code/Communication/Communication.cpp \
    ./Code/main.cpp \
    ./Code/MainWindow/MainWindow.cpp \
    ./Code/Protocols/Protocols.cpp \
    ./Code/SelectedCamera/SelectedCameraWidget.cpp \
    ./Code/SerialPort/SerialPortWidget.cpp \
    ./Code/SystemSettingWidget/SystemControlWidget.cpp \
    ./Code/TakePhotoSettingWidget/TakePhotoSettingWidget.cpp
RESOURCES += CameraConsole.qrc
